### ISSUE TITLE
一血：希望日后加入历史统计功能

### ISSUE THREAD

**Issue by tanpengsccd** [chaos-zhu/easynode#1]
一血：希望日后加入历史统计功能

**Comment by chaos-zhu** [comment]
> 一血：希望日后加入历史统计功能

统计啥，流量吗？

**Comment by tanpengsccd** [comment]
主要是 在线率 ，延迟，网速

**Comment by 75cnpl** [comment]
延迟延迟，强烈建议加延迟检测，有些鸡太需要这个东西了

**Comment by chaos-zhu** [comment]
#16 已支持http延迟(环境限制，只能检测前端本地到服务器的http延迟

**Comment by tanpengsccd** [comment]
如果能检测 服务器到 给定 IP/URL 之间的延迟 会更好.
