### ISSUE TITLE
Safari访问无法弹出登录页面

### ISSUE THREAD

**Issue by mk87878** [chaos-zhu/easynode#10]
你好，Safari访问无法弹出登录页面，iPad和Mac上都不行，Mac上看到页面加载后控制台有个报错

SyntaxError: Invalid regular expression: invalid group specifier name
promiseReactionJob

Safari版本
Version 15.5 (17613.2.7.1.8)

**Comment by chaos-zhu** [comment]
win开发的，晚上用iPad调试看看

**Comment by chaos-zhu** [comment]
> Invalid regular expression: invalid group specifier name
> promiseReactionJob

使用了Fafari不支持的正则断言. 已修复，待发布.
