### ISSUE TITLE
能把粘贴复制的权限给个选择操控吗

### ISSUE THREAD

**Issue by truewhile** [chaos-zhu/easynode#104]
现在粘贴复制需要https环境，但是这个东西部署到nas上只是在局域网环境用的话就没必要https环境吧，这块现在是强制的，能不能弄个选项，交给用户选择，或者判断请求的地址是局域网地址，还是公网地址，再去做这个限制

**Comment by chaos-zhu** [comment]
有空弄一下

**Comment by chaos-zhu** [comment]
最新版已实现

**Comment by truewhile** [comment]
复制和粘贴还是需要https协议才行啊，我的意思是能不能把必须https这个限制给个控制，毕竟本地局域网搭建不需要考虑安全的问题，外网访问需要https我可以理解，但是局域网访问是不是可以把协议给放宽，让用户选择可以在http协议下也可以复制粘贴
