### ISSUE TITLE
如何调用ssl使用https访问

### ISSUE THREAD

**Issue by Skylush** [chaos-zhu/easynode#105]
<img width="850" alt="image" src="https://github.com/user-attachments/assets/83e06004-c682-48a6-8603-c6a5b7d47930">
<img width="734" alt="image" src="https://github.com/user-attachments/assets/c542d70a-46fe-4cc3-a698-5df86b2d07b3">
请问下怎么配置ssl证书，实现https访问，没有找到nginx文件，证书和key以传入容器中，辛苦帮忙解答一下

**Comment by chaos-zhu** [comment]
建议nginx转发到端口，配置https

**Comment by chaos-zhu** [comment]
贴一个nginx server配置，供参考：
  server {
    listen 443 ssl http2;
    server_name your_domain;
    location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_pass http://127.0.0.1:8082; # your easynode server port
    }
  }
