### ISSUE TITLE
脚本库问题

### ISSUE THREAD

**Issue by lujiang-2020** [chaos-zhu/easynode#109]
比较喜欢2.0.0的实例配置UI，但这个版本不存在脚本库，希望能够加上

**Comment by chaos-zhu** [comment]
暂时没时间去做这个，后面得空了可能会加上UI主题切换

**Comment by lujiang-2020** [comment]
> 暂时没时间去做这个，后面得空了可能会加上UI主题切换

好的，期待早日上线
