### ISSUE TITLE
有个小建议 希望大佬考虑一下

### ISSUE THREAD

**Issue by akasls** [chaos-zhu/easynode#110]
项目非常棒，但有几个不是很方便的地方，希望大佬考虑一下。
1.菜单“连接终端”放在实例配置页面也左上角或右上角更加方便
2.目前脚本库的脚本都是点一下就直接运行了，有时候想在脚本后面加就用不了脚本库，可以加一个只粘贴命令到终端的开关。
3.脚本库的自带命令移到批量指令，这几个命令基本就用一次就用不到了，用脚本库频率高太影响使用了。

**Comment by chaos-zhu** [comment]
1. 菜单切换也没啥不方便的
2. 这个我下个版本加到终端设置里
3. 批量指令页只用来运行批量指令，不涉及脚本。后面我想下怎么优化吧

**Comment by chaos-zhu** [comment]
2.2.7版本实现脚本自动执行开关
