### ISSUE TITLE
最新版本发现无法移除实例

### ISSUE THREAD

**Issue by dianso** [chaos-zhu/easynode#112]
最新版本发现无法移除实例

当前版本: v2.2.8 (最新)

提示已移除，但是还在

**Comment by chaos-zhu** [comment]
已修复，重新拉下镜像

**Comment by vpsad** [comment]
> 已修复，重新拉下镜像

10月22日下载最新2.2.8版本项目文件运行后，删除依然不起作用。包括单实例删除，多实例批量删除。
