### ISSUE TITLE
大佬能否添加高危命令过滤的功能  

### ISSUE THREAD

**Issue by 18166297617** [chaos-zhu/easynode#119]
在实际使用现场防止有人删库跑路

**Comment by chaos-zhu** [comment]
这咋防。。。真有心的人靠这可防不住

**Comment by 18166297617** [comment]
这样我们最少能控制一下哪些命令是不能输出的&nbsp;&nbsp;因为我们有一个现场的人用rm -rf 删错了文件&nbsp; 被批评了&nbsp; &nbsp;&nbsp;
我想着就常用的高危命令如[rm -rf,sudo]&nbsp; 让他无法执行命令就行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月6日(星期三) 晚上9:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chaos-zhu/easynode] 大佬能否添加高危命令过滤的功能   (Issue #119)














 
这咋防。。。真有心的人靠这可防不住

**Comment by chaos-zhu** [comment]
无计划支持

**Comment by ssln5014** [comment]
> 这样我们最少能控制一下哪些命令是不能输出的&nbsp;&nbsp;因为我们有一个现场的人用rm -rf 删错了文件&nbsp; 被批评了&nbsp; &nbsp;&nbsp; 我想着就常用的高危命令如[rm -rf,sudo]&nbsp; 让他无法执行命令就行了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年11月6日(星期三) 晚上9:58 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [chaos-zhu/easynode] 大佬能否添加高危命令过滤的功能 (Issue #119) 这咋防。。。真有心的人靠这可防不住 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个可以在ash或zsh里安装插件禁用
