### ISSUE TITLE
一键脚本安装后cpu100%

### ISSUE THREAD

**Issue by yfzuix** [chaos-zhu/easynode#12]
系统:centos7 debian10
纯净系统安装完成后,或者重启后执行`pm2 start easynode-server`之后,CPU立马飙到100%

日志截图：

![](https://s3.bmp.ovh/imgs/2022/07/01/a7cf13f3662b6b1b.png)

`top`截图：

<img src = 'https://s3.bmp.ovh/imgs/2022/07/01/5e1521f40d22f5a4.png' />

这两个截图感觉看不出来很异常的地方，然后我装aapanel用任务管理器发现CPU占用最高的是ssh服务
[![jlGsFx.png](https://s1.ax1x.com/2022/07/01/jlGsFx.png)](https://imgtu.com/i/jlGsFx)

**Comment by chaos-zhu** [comment]
在win10试开了台ubuntu虚拟机安装环境后可以正常跑，拉源码调试下。ssh服务只有开终端才会启动
