### ISSUE TITLE
[BUG]同IP实例SFTP问题

### ISSUE THREAD

**Issue by zyz0323** [chaos-zhu/easynode#120]
上次提过了[同一个IP地址无法添加多个实例](https://github.com/chaos-zhu/easynode/issues/98#top)的Issue

更新版本后发现了一个问题

我用EasyNode连接虚拟机
结果发现SFTP文件管理连上的是宿主机的
宿主机和虚拟机都在我的EasyNode实例列表中
宿主机端口是22
虚拟机是我自定义的端口
两个机器IP一样

**Comment by chaos-zhu** [comment]
@zyz0323 3.0.1版本已修复此问题
