### ISSUE TITLE
plus授权无法移除

### ISSUE THREAD

**Issue by Ronin52658** [chaos-zhu/easynode#125]
对需要经常迁移的用户很不友好

**Comment by Ronin52658** [comment]
动态ip更新后也会占用一个授权

**Comment by gtgc2005** [comment]
的确，诸如hinet这类的动态Ip的机子都会占用授权。也无法安装在NAS上，建议修改授权逻辑。我有3个修改建议供开发者参考

1、保留目前的授权逻辑，但是同ip如果7天没有使用记录，则释放额度。

2、修改授权逻辑，增加反激活逻辑，主动操作释放额度

3、减少授权额度，但是改为同时在线额度    5ip改3ip  3ip改1ip

以上1跟2目前看来也无法解决家庭NAS环境跟动态ip环境使用，但是对经常迁移用户友好  3可以完美解决动态ip环境使用。

**Comment by Ronin52658** [comment]
动态ip多次更换ip后授权掉了

**Comment by chaos-zhu** [comment]
@Ronin52658 @gtgc2005 感谢提供建议。目前看使用IP授权的方式无法解决动态ip的问题。手动移除授权，限制ip变得没有意义，因为不会有人在很多台机器上同时安装这个面板

IP授权检测服务目前还是初版，只是记录激活的ip数量，激活时间、同时在线检测的功能目前都没有实现的，暂时也没那个精力投入大量时间去做，后面主要空闲时间还是会优先开发功能点。

至于部署在动态IP的VPS上，后面会上架限制n多个ip的授权码，保证天天换都有的用，至于价格可能会偏贵，毕竟用得起这种VPS还能经常切IP的人也不差这点钱

然后是家庭的NAS上，暂时没有很好的解决办法。或者建议部署在NAS对端的静态IP服务器上。

最后再次感谢。先close了
