### ISSUE TITLE
plus版key的问题，急需解决

### ISSUE THREAD

**Issue by ToHappyBirth** [chaos-zhu/easynode#134]
![image](https://github.com/user-attachments/assets/b77efed4-1b97-4095-a294-ec1373172c9b)

同一个电脑，只是更新了几次版本，然后提示key不能用了。

买的key是5IP的永久key。你这个IP是不是应该有页面可以支持解绑呢？

**Comment by chaos-zhu** [comment]
本地跑，宽带不是固定的IP，每次更换都会消耗IP额度。至于支持解绑可以参考#125
