### ISSUE TITLE
没安装成功？

### ISSUE THREAD

**Issue by souying** [chaos-zhu/easynode#15]
![image](https://user-images.githubusercontent.com/20512945/185577088-c142de23-02e0-4ee2-bca6-288adfa8e684.png)
打开ip:8082  显示  选择手动安装的  按步骤走的

**Comment by souying** [comment]
没前端的东西？？

**Comment by chaos-zhu** [comment]
> ![image](https://user-images.githubusercontent.com/20512945/185577088-c142de23-02e0-4ee2-bca6-288adfa8e684.png) 打开ip:8082 显示 选择手动安装的 按步骤走的

cd到server再执行yarn，一切正常

**Comment by souying** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
