### ISSUE TITLE
可以打包docker的arm64镜像吗

### ISSUE THREAD

**Issue by CLAY-CMD** [chaos-zhu/easynode#24]
最近看了看大佬写的这个项目确实不错，本来想体验体验的。但是我想在我arm上跑这个docker镜像，发现镜像只支持amd64的。所以能否打包arm64的镜像，假如可以的话就非常感谢了。

**Comment by chaos-zhu** [comment]
客户端有arm包，服务端的有空构建个吧

**Comment by CLAY-CMD** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by chaos-zhu** [comment]
已发布
