### ISSUE TITLE
webssh 连接 域名 host  可连接ssh 但是无法获取硬件信息.

### ISSUE THREAD

**Issue by tanpengsccd** [chaos-zhu/easynode#26]

**Comment by tanpengsccd** [comment]
好几个鸡 无法获取硬件信息... 
和 是不是 域名连接无关.

**Comment by chaos-zhu** [comment]
> 好几个鸡 无法获取硬件信息... 和 是不是 域名连接无关.

跟域名链接没关系。看看客户端日志 `systemctl status easynode-client`
