### ISSUE TITLE
10605 ExecStart=/root/local/easynode-client/arm的客服端报easynode-client (code=exited, status=1/FAILURE)

### ISSUE THREAD

**Issue by wu17481748** [chaos-zhu/easynode#27]

**Comment by wu17481748** [comment]
日志
easynode-client.service: Failed with result 'exit-code'

**Comment by chaos-zhu** [comment]
> chmod -R 777 /root/local/easynode-client/easynode-client后跑起来了倒是ip:22022页面not found

客户端22022端口只跟服务端websocket交互，ui页面在服务端, 端口8082

**Comment by wu17481748** [comment]
刚开始装服务端和客服端，服务端ip:8082正常进去客服端报错chmod -R 777 /root/local/easynode-client/easynode-client后，重启系统服务端报错进不了ip:8082   客服端正常运行。

**Comment by wu17481748** [comment]
刚开始装服务端和客户端，服务端ip:8082正常进去客户端报错，chmod -R 777 /root/local/easynode-client/easynode-client后重启系统服务端报错进不了ip:8082   客户端正常运行。
![Screenshot_2022-12-13-15-25-30-276_bin mt plus](https://user-images.githubusercontent.com/106220792/207253344-644c0014-2fa6-4d90-b256-a42a829b001f.jpg)
