### ISSUE TITLE
能否在启动的时候增加自定义前缀

### ISSUE THREAD

**Issue by yingbibo-tim** [chaos-zhu/easynode#30]
作者你好,能否在应用启动的时候自定义增加路由前缀 比如 原先请求 http://ip:8082/xxx 然后可以自定义 http://ip:8082/prefix/xxx 
包含js的请求 及 接口的请求这样

**Comment by chaos-zhu** [comment]
node服务倒是可以自定义: https://github.com/chaos-zhu/easynode/blob/v1.2/server/app/config/index.js#L15

前端js也是可以的，之前有计划用nuxt3重构前后端，但是发现nuxt3不太适合写后端服务. 等会我开源下前端

**Comment by chaos-zhu** [comment]
前端仓库地址：https://github.com/chaos-zhu/easynode_web
