### ISSUE TITLE
ubuntu20 安裝后反复login

### ISSUE THREAD

**Issue by catding** [chaos-zhu/easynode#33]
在ubuntu16/20 上自动安装后，admin登录成功后，反复login，没法进行任何操作。。。
安装没有报错，但是login后又弹出来，无限往复。
求助。。

**Comment by chaos-zhu** [comment]
pm2 log看一下日志

**Comment by catding** [comment]
感谢回复。这样的
root@mail:~# pm2 log

Command 'pm2' not found, did you mean:

  command 'pom2' from deb libpod-pom-perl (2.01-3)
  command 'pm' from deb powerman (2.3.5-1build2)
  command 'pmw' from deb pmw (1:4.30-1)
  command 'gm2' from deb gm2 (4:10.0-1ubuntu2)
  command 'pmc' from deb linuxptp (1.9.2-1)
  command 'pms' from deb pms (0.42-1build4)
  command 'wm2' from deb wm2 (4+svn20090216-4build1)
  command 'pmi' from deb powermanagement-interface (0.3.21)

Try: apt install <deb name>

root@mail:~# netstat -ltpun|grep node
tcp6       0      0 :::22022                :::*                    LISTEN      1563324/node /root/
tcp6       0      0 :::8082                 :::*                    LISTEN      1563324/node /root/

**Comment by chaos-zhu** [comment]
pm2没装上啊，用docker试试
