### ISSUE TITLE
希望能增加文件夹上传功能

### ISSUE THREAD

**Issue by cn-src** [chaos-zhu/easynode#34]
我目前用的 https://github.com/Jrohy/webssh 可以支持。

**Comment by chaos-zhu** [comment]
2.0计划开发中...

**Comment by tecleon** [comment]
请问这个功能正在开发了吗？

**Comment by chaos-zhu** [comment]
@cn-src @tecleon 该功能v2.1.6已支持

**Comment by tecleon** [comment]
> @cn-src @tecleon 该功能v2.1.6已支持

好的
