### ISSUE TITLE
无法读取监控信息

### ISSUE THREAD

**Issue by cn-src** [chaos-zhu/easynode#37]
![image](https://user-images.githubusercontent.com/8263180/220833959-13b37213-eb6d-4f60-ae70-484b6b3123d4.png)

**Comment by chaos-zhu** [comment]
什么环境?

**Comment by cn-src** [comment]
> 什么环境?

是防火墙的原因，看看能否加个提示。

**Comment by chajiuqqq** [comment]
我也看不到监控，ufw没开，系统Ubuntu 22.04.2 LTS，是啥问题嘞

![image](https://github.com/user-attachments/assets/d1746bbc-fbda-4043-a51c-426c5b7a2779)
