### ISSUE TITLE
一键安装脚本需要修复

### ISSUE THREAD

**Issue by cloudswave** [chaos-zhu/easynode#38]
可以将脚本：https://github.com/chaos-zhu/easynode/blob/v1.2/easynode-server-install.sh
中的`https://gitee.com/chaoszhu_0/nvm-cn/raw/master/install.sh`修改成`https://gitee.com/RubyKids/nvm-cn/raw/main/install.sh`,否则会安装失败
```
HEAD 目前位于 9600617... v0.39.1
=> 添加nvm环境变量(Bash,Zsh)
=> 使用淘宝镜像
=> 安装nvm-update,升级更新请使用该命令
curl: (22) The requested URL returned error: 404 Not Found
安装失败

```

**Comment by chaos-zhu** [comment]
已移除基础运行环境安装
