### ISSUE TITLE
docker版本sftp打开文件报错

### ISSUE THREAD

**Issue by cloudswave** [chaos-zhu/easynode#39]
arm服务器docker安装easynode后可正常登陆ssh连接服务器，但是sftp打开文件时弹报错信息：
```
fastGet->fastGet: Bad path: /easynode-server/app/socket/sftp-cache/.profile: /easynode-server/app/socket/sftp-cache: not exist
```
<img width="719" alt="截屏2023-03-11 下午8 45 20" src="https://user-images.githubusercontent.com/5915548/224485302-98394e9e-abb8-4ee3-8030-e067c51caf07.png">

**Comment by cloudswave** [comment]
过一会又自动好了，不知道是不是因为网络问题？

**Comment by chaos-zhu** [comment]
暂未复现，有问题重开issue
