### ISSUE TITLE
SFTP 无法编辑文件问题。附：解决方法。

### ISSUE THREAD

**Issue by weongit** [chaos-zhu/easynode#40]
一键安装，连接SSH，打开SFTP，再打开任意文件后提示：fastGet->fastGet: Bad path: /root/easynode-server/app/socket/sftp-cache/libaudit.conf: /root/easynode-server/app/socket/sftp-cache: not exist
此错误可用以下方法解决：
在/root/easynode-server/app/socket/该目录下，创建文件夹【sftp-cache】后，就可以正常编辑文件了。

然后，感谢大佬开源这么好用的工具。

**Comment by chaos-zhu** [comment]
上传文件的缓存文件夹被git忽略掉了，已修复。
