### ISSUE TITLE
主机数量超出12个后，排序功能无法使用

### ISSUE THREAD

**Issue by weongit** [chaos-zhu/easynode#41]
您好，这边测试用下来发现以下问题：
Debian11，使用一键脚本安装的，各项功能都正常使用。但是在主机排序时发现当主机数量超过12个后，无法排序，因为排序界面显示的主机数量就只有12个。超出12个数量后，排序界面不显示。（当主机数量为12个以下时，是可以正常排序的。）

仅反馈使用中遇到的问题，感谢大佬开源。

**Comment by chaos-zhu** [comment]
没添加过那么多机器，有空尝试下

**Comment by chaos-zhu** [comment]
2.0通过index排序，不再手动拖拽
