### ISSUE TITLE
客户端认证问题

### ISSUE THREAD

**Issue by TaoChan1005** [chaos-zhu/easynode#42]
服务端好像可以不经过客户端就可以直接添加？

**Comment by chaos-zhu** [comment]
你的意思是直接写在文件里还是调API？

**Comment by TaoChan1005** [comment]
我在两台服务器上部署了两个docker（server端，A和B），然后在A里面添加B的信息（这一步只填写了B的IP），我就可以在A里面看见B的内存和CPU使用了。
