### ISSUE TITLE
希望增加docker版服务器端数据目录或批量导入导出主机

### ISSUE THREAD

**Issue by coolxy** [chaos-zhu/easynode#43]
希望增加docker版服务器端数据目录或批量导入导出主机
每次重新部署docker版后要重新一个一个录入，能增加数据目录或批量导入导出主机就更好了

**Comment by chaos-zhu** [comment]
支持docker数据卷挂载，同一台机器重新部署不用重复添加机器的，看下/easynode-server目录有没有文件

**Comment by chaos-zhu** [comment]
> > 支持docker数据卷挂载，同一台机器重新部署不用重复添加机器的，看下/easynode-server目录有没有文件
> 
> /easynode-server下没有文件，连隐藏文件都没有

已修复. 有问题再开
