### ISSUE TITLE
菜鸟问个问题

### ISSUE THREAD

**Issue by woshichenghaibo** [chaos-zhu/easynode#46]
有服务器监控就行了，打开浏览器不是就可以访问了？那为何还要安装客户端呢？

**Comment by chaos-zhu** [comment]
> 有服务器监控就行了，打开浏览器不是就可以访问了？那为何还要安装客户端呢？

这里客户端的意思是被监控的机器，可以添加多台

**Comment by woshichenghaibo** [comment]
> > 有服务器监控就行了，打开浏览器不是就可以访问了？那为何还要安装客户端呢？
> 
> 这里客户端的意思是被监控的机器，可以添加多台

如果我只是监控一台机器，是不是就安装服务器端就行？

**Comment by chaos-zhu** [comment]
> > > 有服务器监控就行了，打开浏览器不是就可以访问了？那为何还要安装客户端呢？
> > 
> > 
> > 这里客户端的意思是被监控的机器，可以添加多台
> 
> 如果我只是监控一台机器，是不是就安装服务器端就行？

是的

**Comment by woshichenghaibo** [comment]
> > > > 有服务器监控就行了，打开浏览器不是就可以访问了？那为何还要安装客户端呢？
> > > 
> > > 
> > > 这里客户端的意思是被监控的机器，可以添加多台
> > 
> > 
> > 如果我只是监控一台机器，是不是就安装服务器端就行？
> 
> 是的

还是没搞明白，我现在家里有一个随身WIFI装了debian系统嗯，用CF做了内网穿透。我现在在上面安装了服务端和客户端，都安装了。我用互联网访问8082端口，能打开网页，但是打开网页之后，服务器连不上，连接服务器需要填IP地址，但是IP地址是没有的，因为我没有公网IP，它上面默认的是CF套用的IP，我怎么才能看到服务器的状态？

**Comment by chaos-zhu** [comment]
一台机器只需要安装服务端就行，客户端不需要单独再安装。如果要查看内网的机器状态，需要映射8082和22022两个端口
