### ISSUE TITLE
服务器每次重启都会添加一个server-side-host

### ISSUE THREAD

**Issue by RiversSong** [chaos-zhu/easynode#51]
每次删除了之后，服务器重启server-side-host又给我添加回去了，如图，在哪里能关闭这个功能吗？
![image](https://github.com/chaos-zhu/easynode/assets/24579606/cd99ed9b-6042-4622-a56e-de8ca4d45bc7)

**Comment by chaos-zhu** [comment]
下个版本修复

**Comment by chaos-zhu** [comment]
服务端将不再默认支持客户端，2.0已修复
