### ISSUE TITLE
安装可以用，重启之后就无法启动了

### ISSUE THREAD

**Issue by LebsChen** [chaos-zhu/easynode#61]
/root/.pm2/logs/easynode-server-error.log last 15 lines:
0|easynode |   requireStack: []
0|easynode | }
0|easynode | Error: Cannot find module '/root/easynode-server'
0|easynode |     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
0|easynode |     at Module._load (node:internal/modules/cjs/loader:901:27)
0|easynode |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|easynode |     at Module._compile (node:internal/modules/cjs/loader:1233:14)
0|easynode |     at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
0|easynode |     at Module.load (node:internal/modules/cjs/loader:1091:32)
0|easynode |     at Module._load (node:internal/modules/cjs/loader:938:12)
0|easynode |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
0|easynode |     at node:internal/main/run_main_module:23:47 {
0|easynode |   code: 'MODULE_NOT_FOUND',
0|easynode |   requireStack: []
0|easynode | }

**Comment by chaos-zhu** [comment]
误删文件了吧

**Comment by chaos-zhu** [comment]
先关了，2.0应该没这个问题了
