### ISSUE TITLE
希望能丰富通知方式

### ISSUE THREAD

**Issue by holddyxu** [chaos-zhu/easynode#71]
1.增加支持的邮件类型，目前的三个类型有些少，希望后期可以增加其他邮箱，或者开放自定义邮箱设置
2.添加 例如TG,企业微信等方式进行通知

**Comment by chaos-zhu** [comment]
后面抽时间写一下

**Comment by chaos-zhu** [comment]
邮箱已经放开，支持市面大多数邮箱SMTP配置。另外新增了Server酱，其他的通知方案暂时没空写了
