### ISSUE TITLE
期待大佬能够丰富一些常用功能

### ISSUE THREAD

**Issue by NikoYomi** [chaos-zhu/easynode#74]
期待大佬能够丰富一些常用功能

- 备份导入和导出
- 常用快捷指令
- 显示延迟
- 文件上传到服务器

**Comment by chaos-zhu** [comment]
1. 最新版导入导出均以支持
2. 快捷指令说的是面板中的脚本功能?
3. 延迟显示对于浏览器本地来讲目前还没找到特别好的方案去实现
4. sftp中支持上传与下载

**Comment by NikoYomi** [comment]
> 1. 最新版导入导出均以支持
> 2. 快捷指令说的是面板中的脚本功能?
> 3. 延迟显示对于浏览器本地来讲目前还没找到特别好的方案去实现
> 4. sftp中支持上传与下载

一直更新最新版！大佬真是太厉害了！目前2说的是，一些常用的快捷指令，比如像finalshell一样，可以自己创建一些指令，只需要点一下就能输入到控制台。（像我这样经常记不住命令行的小白来讲简直就是福音...）

![Screenshot - 2024-08-09 14 32 58](https://github.com/user-attachments/assets/b034682d-36e2-4475-a85f-bbafe1518420)
![Screenshot - 2024-08-09 14 33 13](https://github.com/user-attachments/assets/df700d3a-7eb5-4bfb-9c99-ba396a061b5e)

**Comment by chaos-zhu** [comment]
就是面板的脚本，在终端页面可以看到，一键输入脚本，参数功能目前还不支持
