### ISSUE TITLE
sftp建议增加输入路径切换的功能，如图

### ISSUE THREAD

**Issue by tecleon** [chaos-zhu/easynode#75]
<img width="509" alt="ca075e4368e9eafecc97671b9af7100" src="https://github.com/user-attachments/assets/a8313f9c-a786-4bcf-b064-2c486d900791">

**Comment by chaos-zhu** [comment]
v2.1.4已支持终端输入cd 指令 SFTP面板同步路径(目前只支持cd 全路径，且不支持~特殊符号)

**Comment by chaos-zhu** [comment]
v2.2.4已支持路径输入跳转
