### ISSUE TITLE
有计划添加2FA吗

### ISSUE THREAD

**Issue by nankaine** [chaos-zhu/easynode#77]
暴露在外网的设备，希望能增加一个2FA。

**Comment by chaos-zhu** [comment]
这个后面有空再写，不是很建议暴露在外网。登录爆破已经做了一些限制了(例如登录失败5次就会禁止登录5分钟,且会发送通知)，使用iptables应该比2FA更安全点

**Comment by koujiangqq** [comment]
我也希望能增加一个2FA。

**Comment by chaos-zhu** [comment]
已实现
