### ISSUE TITLE
请问有没有加入终端审计日志的功能计划

### ISSUE THREAD

**Issue by tecleon** [chaos-zhu/easynode#78]
一般在终端执行命令属于高危操作，最好有日志记录，可以考虑下把用户输入的命令、时间、IP、用户这些都记录下来。

**Comment by chaos-zhu** [comment]
有哪些终端软件带这个功能的吗，我参考参考

**Comment by tecleon** [comment]
可以看看这个：https://github.com/ops-coffee/webssh?tab=readme-ov-file
终端有录像记录，有实时监控和强制上下线

**Comment by chaos-zhu** [comment]
> 可以看看这个：https://github.com/ops-coffee/webssh?tab=readme-ov-file 终端有录像记录，有实时监控和强制上下线

历史记录后面可能会写，其他功能暂时没想法

**Comment by DecemJiang** [comment]
这个是个很好的项目，如果加上多用户管理和审计功能，将是一个很好的ssh堡垒服务。

**Comment by chaos-zhu** [comment]
暂时没想做那么专业化，先close了
