### ISSUE TITLE
监控客户端希望能支持交换分区实时显示、docker部署

### ISSUE THREAD

**Issue by koujiangqq** [chaos-zhu/easynode#82]
监控客户端希望能支持交换分区实时显示、docker部署

**Comment by chaos-zhu** [comment]
v2.1.7已支持交换内存展示，需更新客户端展示

客户端docker自行编译

**Comment by koujiangqq** [comment]
大佬给力☆(￣▽￣)/$:*
docker客户端不会编译，因为用的alpline,命令安装监控端无法使用
