### ISSUE TITLE
sftp上传大文件夹会出现报错

### ISSUE THREAD

**Issue by tecleon** [chaos-zhu/easynode#83]
sftp上传文件夹会出现报错，并且刚上传的时候未显示上传进度
![image](https://github.com/user-attachments/assets/b5c022ec-e672-456f-8213-ed7087ba4299)

**Comment by chaos-zhu** [comment]
哪个版本？

**Comment by tecleon** [comment]
今天拉的最新的代码

**Comment by chaos-zhu** [comment]
> 今天拉的最新的代码

看你右上角有新版本检测到，应该不是最新的版本，我测试过几轮上传没复现你的问题

![image](https://github.com/user-attachments/assets/6b3c2b70-3057-44f4-8173-58333529cc48)
![image](https://github.com/user-attachments/assets/227d71a4-03b7-467e-a919-ba15b23bb222)

**Comment by tecleon** [comment]
今天拉了最新的代码，还是报错
![597b71d7e63b68a816492a4b7587fdb](https://github.com/user-attachments/assets/3bd65845-c55c-4b21-bb41-4d22936b538a)

**Comment by chaos-zhu** [comment]
我这边没办法复现，方便的话移除下敏感文件，打包个zip发我试试

**Comment by tecleon** [comment]
[
[Uploading resource.zip…]()
](url)

**Comment by tecleon** [comment]
[resource.zip](https://github.com/user-attachments/files/16668168/resource.zip)
@chaos-zhu 麻烦帮忙看看

**Comment by chaos-zhu** [comment]
验证过了，应该是上传的过程的中有切换目录的操作，最新版在有sftp任务进行的时候禁止了操作。后续有空再优化吧
