### ISSUE TITLE
我将那个server打包成一个liunx可执行程序  然后在liunx x86 上运行报错 段错误

### ISSUE THREAD

**Issue by 18166297617** [chaos-zhu/easynode#92]
![image](https://github.com/user-attachments/assets/76b90eaa-a965-4f2e-890c-615dfe43cf70)

**Comment by chaos-zhu** [comment]
你改代码了吧 ，源码里没这个关键字

**Comment by 18166297617** [comment]
是的改过代码
公司有需求要把你这套东西部署到不同的客户手上,如果要安装node环境的话就会比较麻烦 所以想到把你这个这套服务端也像你的那个client一样打包成一个可执行程序 傻瓜式的安装到客户的环境里面 客户的环境是一套独立的网络不通外网的那种
大佬 这种方式可行吗









 
***@***.***











Original:
From：chaos-zhu ***@***.***>Date：2024-08-23 16:13:55(中国 (GMT+08:00))To：chaos-zhu/easynode ***@***.***>Cc：18166297617 ***@***.***> , Author ***@***.***>Subject：Re: [chaos-zhu/easynode] 我将那个server打包成一个liunx可执行程序 然后在liunx x86 上运行报错 段错误 (Issue #92)
你改代码了吧 ，源码里没这个关键字

**Comment by 18166297617** [comment]
![image](https://github.com/user-attachments/assets/808a2eca-c5e7-4835-99a1-17c86e704113)
就是在这个 server加了一个pkg打包

**Comment by chaos-zhu** [comment]
客户机器上没docker吗，直接docker多少。pkg很久没维护了，构建个小应用还行，代码复杂了就难免各种问题
