### ISSUE TITLE
连接失败: All configured authentication methods failed

### ISSUE THREAD

**Issue by finexss** [chaos-zhu/easynode#94]
服务器系统ubuntu 22.04
防火墙开启80和443端口
部署方式Docker：
docker run -d -p 80:8082 --restart=always -v /root/easynode/db:/easynode/app/db chaoszhu/easynode
域名在CF上开启代理通过HTTPS方式访问的。设置好ssh后点连接终端，报错：
连接失败: All configured authentication methods failed

通过http://IP/ 来访问，一样的提示错误：
连接失败: All configured authentication methods failed

是不是还需要开启别的什么端口？

**Comment by chaos-zhu** [comment]
端口没开一般会报timeout。看看ssh连接错误的日志

**Comment by finexss** [comment]
> 端口没开一般会报timeout。看看ssh连接错误的日志

浏览器F12里没有错误，是要看docker里的日志吗？
我使用另一个sshwifty项目出现的也是同样的错误。

**Comment by chaos-zhu** [comment]
> > 端口没开一般会报timeout。看看ssh连接错误的日志
> 
> 浏览器F12里没有错误，是要看docker里的日志吗？ 我使用另一个sshwifty项目出现的也是同样的错误。

看ssh连接日志，不是docker日志，大概率是ssh密钥加密方式太老，安全标准低，跟你Linux服务器默认支持的加密方式不一样，需要设置

**Comment by finexss** [comment]
> > > 端口没开一般会报timeout。看看ssh连接错误的日志
> > 
> > 
> > 浏览器F12里没有错误，是要看docker里的日志吗？ 我使用另一个sshwifty项目出现的也是同样的错误。
> 
> 看ssh连接日志，不是docker日志，大概率是ssh密钥加密方式太老，安全标准低，跟你Linux服务器默认支持的加密方式不一样，需要设置

是的，找到原因了，改用了密钥登陆就可以的。加密方式的原因，感谢回复！
