### ISSUE TITLE
同一个IP地址无法添加多个实例

### ISSUE THREAD

**Issue by zyz0323** [chaos-zhu/easynode#98]
如题，比如我有两台NAT服务器，两台IP一样
一台是xxx.xxx.xxx.xxx:12345
另一台是xxx.xxx.xxx.xxx:23456
EasyNode不支持添加多个IP一样的实例

**Comment by chaos-zhu** [comment]
暂时不支持，目前使用ip来判断实例重复的，后面有空改成ip+port

**Comment by chaos-zhu** [comment]
暂时不支持，目前使用ip来判断实例重复的，后面有空改成ip+port

**Comment by chaos-zhu** [comment]
@zyz0323 最新版已支持同IP任意端口添加实例
